import { OnlineStatusProvider } from "../context/OnlineStatusContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import { Toaster } from "sonner";
import OfflineWatcher from "./components/OfflineWatcher";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "choosepdf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
       
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');var isDark=t? t==='dark' : window.matchMedia('(prefers-color-scheme: dark)').matches;var e=document.documentElement;if(isDark){e.classList.add('dark')}else{e.classList.remove('dark')}}catch(e){}})();`,
          }}
        />
        <Navbar />
        <OnlineStatusProvider>
          <OfflineWatcher />
          {children}
        </OnlineStatusProvider>
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
